[package]
name = "spong/amm"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Red = "red-blox/red@2.3.0"
fusion = "plainsour/lemon@0.3.0-dev.5.6"
lemonsignal = "data-oriented-house/lemonsignal@1.10.0"

[server-dependencies]
datakeep = "noahrepublic/datakeep@3.1.2"